Add '-lfreetype' to LIBS to prevent build error
Creating executable: attract
/usr/bin/ld: obj/libgameswf.a(gameswf_freetype.o): undefined reference to symbol 'FT_Done_FreeType'
/usr/bin/ld: /lib/aarch64-linux-gnu/libfreetype.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Signed-off-by: Dongjin Kim <tobetter@gmail.com>